type Navigation<T> = {
  [key: string]: Navigation<T> | T;
};

type Lexicon = {
  [key: string]: string;
};

type AntiPattern = {
  name: string;
  aka?: string[];
  problem: string;
  solution: string;
};

type Pattern = {
  name: string;
  intent: string;
  problem: string;
  structure: string;
  checkList: string[];
};

const content: {
  lexicon: Lexicon;
  "anti-patterns": Navigation<AntiPattern>;
  patterns: Navigation<Pattern>;
} = {
  lexicon: {
    "anti-pattern": "a coding practice which generates negative consequences",
    "far-coupled": "redundant or indirect associations.",
    stovepipe: "systems with ad-hoc architectures",
    profile: "a defined subset of an interface with conventions around usage",
    singleton:
      "an object which, once instantiated, persists and is shared by all services",
  },
  "anti-patterns": {
    "software-development": {
      "the-blob": {
        name: "The Blob",
        aka: ["Winnebego", "God Class"],
        problem:
          "a single class comprising the majority of application responsibilities",
        solution:
          "refactoring design to distribute responsibilities and isolate change",
      },
      "continuous-obsolescence": {
        name: "Continuous Obsolescence",
        problem:
          "technology becomes obsolete faster than engineers can maintain it",
        solution:
          "design to interfaces/contracts which obscure the effect of obsolete implementations",
      },
      "lava-flow": {
        name: "Lava Flow",
        aka: ["Dead Code"],
        problem:
          "legacy, unreachable, commented, prototype, or etc. code which has not been refactored/removed and is no longer understood",
        solution:
          "code analysis, documentation, deletion, and refactoring/wrapping with configuration management",
      },
      "ambiguous-viewpoint": {
        name: "Ambiguous Viewpoint",
        problem:
          "Object-Oriented Analysis & Design models presented without respect to a distinct viewpoint: user, design, implementation",
        solution:
          "creating explicit and distinct models/diagrams of user, design, and implementation specifications",
      },
      "functional-decomposition": {
        name: "Functional Decomposition",
        aka: ["No OO"],
        problem: "object-oriented code written in a procedural structure",
        solution: "education and adherence to object-oriented design patterns",
      },
      poltergeists: {
        name: "Poltergeists",
        aka: ["Gypsy", "Proliferation of Classes", "Big Dolt Controller Class"],
        problem: "classes with extremely limited roles/lifespans",
        solution: "reallocation of properties to more long-lived classes",
      },
      "boat-anchor": {
        name: "Boat Anchor",
        problem:
          "a piece of software/hardware which serves no meaningful purpose in the application",
        solution:
          "identification of a technical backup which can be implemented at low-cost",
      },
      "golden-hammer": {
        name: "Golden Hammer",
        aka: ["Old Yeller, Head-in-the-Sand"],
        problem:
          "the application of well-known but inappropriate technology to a given problem",
        solution:
          "training and architecture which supports the interoperability of multiple technologies",
      },
      "dead-end": {
        name: "Dead End",
        aka: ["Kevorkian Component"],
        problem:
          "the modification of vendor code such that it is no longer supported by the vendor",
        solution:
          "do not modify third-party applications, design to interfaces to avoid vendor lock-in",
      },
      "spaghetti-code": {
        name: "Spaghetti Code",
        problem: "code which is difficult to extend/maintain",
        solution: "frequent code refactoring and design review/maintenance",
      },
      "input-kludge": {
        name: "Input Kludge",
        problem: "ad-hoc input handling",
        solution: "industry-standard or framework-level input handling",
      },
      "walking-through-a-minefield": {
        name: "Walking Through a Minefield",
        problem: "all software has significant bugs",
        solution: "robust/excessive testing infrastructure",
      },
      "cut-and-paste-programming": {
        name: "Cut & Paste Programming",
        aka: ["Clipboard Coding", "Software Cloning", "Software Propagation"],
        problem: "code which is copied with minor or no modification",
        solution: "refactoring to reusable, configurable classes",
      },
      "mushroom-management": {
        name: "Mushroom Management",
        aka: ["Pseudo-Analysis", "Blind Development"],
        problem: "explicit policy of isolating developers from user feedback",
        solution: "UI/UX development in rapid, minor increments",
      },
    },
    "software-architecture": {
      "autogenerated-stovepipe": {
        name: "Autogenerated Stovepipe",
        problem:
          "when migrating to a distributed model, existing interfaces may make inefficient assumptions",
        solution: "full rewrite of interfaces",
      },
      "stovepipe-enterprise": {
        name: "Stovepipe Enterprise",
        aka: ["Islands of Automation"],
        problem: "software structure which inhibits change",
        solution:
          "selection and implementation of interoperability standards across systems and organizations",
      },
      jumble: {
        name: "Jumble",
        problem:
          "reusability is inhibited by intermixing horizontal and vertical design elements",
        solution: "delegate horizontal design elements into their own layer",
      },
      "stovepipe-system": {
        name: "Stovepipe System",
        aka: ["Legacy System", "Uncle Sam Special", "Ad Hoc Integration"],
        problem: "ad-hoc, point-to-point subsystem integration",
        solution:
          "minimize exposed interfaces, rely on component-style abstractions",
      },
      "cover-your-assets": {
        name: "Cover Your Assets",
        problem:
          "document-driven design leads to obtuse requirements specifications",
        solution: "use blueprints",
      },
      "vendor-lock-in": {
        name: "Vendor Lock-In",
        aka: [
          "Product-Dependent Architecture",
          "Bondage and Submission",
          "Connector Conspiracy",
        ],
        problem: "systems are highly dependent on proprietary architectures",
        solution: "architectural isolation layers",
      },
      "architecture-by-implication": {
        name: "Architecture by Implication",
        aka: ["Wherefore Art Thou Architecture"],
        problem:
          "lack of architecture specification for systems under development",
        solution:
          "extensive modeling of the system from the viewpoints of different stakeholders",
      },
      "warm-bodies": {
        name: "Warm Bodies",
        aka: ["Deadwood", "Body Shop", "Seat Warmers", "Mythical Man-Month"],
        problem: "the vast majority of programmers do a tiny minority of work",
        solution:
          "the ideal team size is four people, the ideal project duration is four months",
      },
      "design-by-committee": {
        name: "Design by Committee",
        aka: [
          "Gold Plating",
          "Standards Disease",
          "Make Everybody Happy",
          "Political Party",
        ],
        problem: "complex and incoherent architectures",
        solution: "distinction of architecture roles and refactoring",
      },
      "swiss-army-knife": {
        name: "Swiss Army Knife",
        problem:
          "excessively complex interface meant to support too many use-cases",
        solution:
          "standardizing usage of a subset of the interface using a profile",
      },
      "reinvent-the-wheel": {
        name: "Reinvent The Wheel",
        aka: ["Design in a Vacuum", "Greenfield System"],
        problem:
          "custom software systems are built even when their functionality exists in legacy software",
        solution: "architecture mining",
      },
      "the-grand-old-duke-of-york": {
        name: "The Grand Old Duke of York",
        aka: [
          "Everyone Charges Up the Hill",
          "Lack of Architecture Instinct",
          "Abstractionist vs Implementationists",
        ],
        problem:
          "software designs which are unnecessarily complex with very little abstraction",
        solution: "distinction of architectural roles",
      },
    },
  },
  patterns: {
    creational: {
      "abstract-factory": {
        name: "Abstract Factory",
        intent: "interface for creating related/dependent objects",
        problem: "platform dependency encapsulation",
        structure:
          "abstract factory delegates to one of any number of factories to instantiate classes implementing the requested interface",
        checkList: [
          "define an abstract factory with methods for every product",
          "define a factory implementation for every  platform",
          "deprecate all instances of new in favor of the abstract factory",
        ],
      },
      builder: {
        name: "Builder",
        intent: "separate the construction objects into multiple steps",
        problem:
          "some objects may be very complex, requiring dynamic construction, or many objects may be constructed from a base configuration",
        structure:
          "the reader parses common input, the builder polymorphically creates many peculiar targets",
        checkList: [
          "is there potential for many outputs",
          "define api for capturing configuration",
          "define builder for deriving target from configuration",
          "client asks reader to construct and builder to return",
        ],
      },
      "factory-method": {
        name: "Factory Method",
        intent: "encapsulate class construction",
        problem:
          "allow applications to define the construction of their own domain objects",
        structure:
          "any constructor method, eg: named constructors, service container",
        checkList: [
          "if relying on polymorphism, consider a static factory method on the base class",
          "consider an object pool/caching",
          "consider actual constructors to be private/protected",
        ],
      },
      "object-pool": {
        name: "Object Pool",
        intent:
          "reduce cost of instantiation by caching and re-using created objects",
        problem:
          "object instantiation can be expensive, object pools cache instantiated objects to avoid recreating them",
        structure:
          "client request object from pool which instantiates it if none are available, and caches it for reuse when the client is finished",
        checkList: [
          "create object pool with private collection of objects",
          "create api to acquire and release objects",
          "use pool as source of objects",
        ],
      },
      prototype: {
        name: " Prototype",
        intent: "create objects by copying others",
        problem:
          "limit configuration management by construct a class once, then create more instances by copying",
        structure:
          "a factory knows how to find a pure, virtual prototype which can then clone itself",
        checkList: [
          "add clone method to class",
          "design registry which contains prototypes",
          "design factory which can look up registry's prototypes and clone the appropriate class",
          "rely on factory instead of new",
        ],
      },
      singleton: {
        name: "Singleton",
        intent: "ensure a class has only one instance",
        problem:
          "the application needs to guarantee only one instance of a class exists",
        structure:
          "the singleton class provides a single accessor function which instantiates and caches the instance on first invocation",
        checkList: [
          "define private, static attribute on class to cache instance",
          "define public, static accessor to return private, static attribute instance",
          "define lazy instantiation so that first invocation of accessor also instantiates class",
        ],
      },
    },
    structural: {},
    behavioral: {},
  },
};

export default content;
