type Navigation<T> = {
  [key: string]: Navigation<T> | T;
};

type Lexicon = {
  [key: string]: string;
};

type AntiPattern = {
  name: string;
  aka?: string[];
  problem: string;
  solution: string;
};

type Pattern = {
  name: string;
  intent: string;
  problem: string;
  structure: string;
};

const content: {
  lexicon: Lexicon;
  "anti-patterns": Navigation<AntiPattern>;
  patterns: Navigation<Pattern>;
} = {
  lexicon: {
    "anti-pattern": "a coding practice which generates negative consequences",
    "far-coupled": "redundant or indirect associations.",
    stovepipe: "systems with ad-hoc architectures",
    profile: "a defined subset of an interface with conventions around usage",
    singleton:
      "an object which, once instantiated, persists and is shared by all services",
  },
  "anti-patterns": {
    "software-development": {
      "the-blob": {
        name: "The Blob",
        aka: ["Winnebego", "God Class"],
        problem:
          "a single class comprising the majority of application responsibilities",
        solution:
          "refactoring design to distribute responsibilities and isolate change",
      },
      "continuous-obsolescence": {
        name: "Continuous Obsolescence",
        problem:
          "technology becomes obsolete faster than engineers can maintain it",
        solution:
          "design to interfaces/contracts which obscure the effect of obsolete implementations",
      },
      "lava-flow": {
        name: "Lava Flow",
        aka: ["Dead Code"],
        problem:
          "legacy, unreachable, commented, prototype, or etc. code which has not been refactored/removed and is no longer understood",
        solution:
          "code analysis, documentation, deletion, and refactoring/wrapping with configuration management",
      },
      "ambiguous-viewpoint": {
        name: "Ambiguous Viewpoint",
        problem:
          "Object-Oriented Analysis & Design models presented without respect to a distinct viewpoint: user, design, implementation",
        solution:
          "creating explicit and distinct models/diagrams of user, design, and implementation specifications",
      },
      "functional-decomposition": {
        name: "Functional Decomposition",
        aka: ["No OO"],
        problem: "object-oriented code written in a procedural structure",
        solution: "education and adherence to object-oriented design patterns",
      },
      poltergeists: {
        name: "Poltergeists",
        aka: ["Gypsy", "Proliferation of Classes", "Big Dolt Controller Class"],
        problem: "classes with extremely limited roles/lifespans",
        solution: "reallocation of properties to more long-lived classes",
      },
      "boat-anchor": {
        name: "Boat Anchor",
        problem:
          "a piece of software/hardware which serves no meaningful purpose in the application",
        solution:
          "identification of a technical backup which can be implemented at low-cost",
      },
      "golden-hammer": {
        name: "Golden Hammer",
        aka: ["Old Yeller, Head-in-the-Sand"],
        problem:
          "the application of well-known but inappropriate technology to a given problem",
        solution:
          "training and architecture which supports the interoperability of multiple technologies",
      },
      "dead-end": {
        name: "Dead End",
        aka: ["Kevorkian Component"],
        problem:
          "the modification of vendor code such that it is no longer supported by the vendor",
        solution:
          "do not modify third-party applications, design to interfaces to avoid vendor lock-in",
      },
      "spaghetti-code": {
        name: "Spaghetti Code",
        problem: "code which is difficult to extend/maintain",
        solution: "frequent code refactoring and design review/maintenance",
      },
      "input-kludge": {
        name: "Input Kludge",
        problem: "ad-hoc input handling",
        solution: "industry-standard or framework-level input handling",
      },
      "walking-through-a-minefield": {
        name: "Walking Through a Minefield",
        problem: "all software has significant bugs",
        solution: "robust/excessive testing infrastructure",
      },
      "cut-and-paste-programming": {
        name: "Cut & Paste Programming",
        aka: ["Clipboard Coding", "Software Cloning", "Software Propagation"],
        problem: "code which is copied with minor or no modification",
        solution: "refactoring to reusable, configurable classes",
      },
      "mushroom-management": {
        name: "Mushroom Management",
        aka: ["Pseudo-Analysis", "Blind Development"],
        problem: "explicit policy of isolating developers from user feedback",
        solution: "UI/UX development in rapid, minor increments",
      },
    },
    "software-architecture": {
      "autogenerated-stovepipe": {
        name: "Autogenerated Stovepipe",
        problem:
          "when migrating to a distributed model, existing interfaces may make inefficient assumptions",
        solution: "full rewrite of interfaces",
      },
      "stovepipe-enterprise": {
        name: "Stovepipe Enterprise",
        aka: ["Islands of Automation"],
        problem: "software structure which inhibits change",
        solution:
          "selection and implementation of interoperability standards across systems and organizations",
      },
      jumble: {
        name: "Jumble",
        problem:
          "reusability is inhibited by intermixing horizontal and vertical design elements",
        solution: "delegate horizontal design elements into their own layer",
      },
      "stovepipe-system": {
        name: "Stovepipe System",
        aka: ["Legacy System", "Uncle Sam Special", "Ad Hoc Integration"],
        problem: "ad-hoc, point-to-point subsystem integration",
        solution:
          "minimize exposed interfaces, rely on component-style abstractions",
      },
      "cover-your-assets": {
        name: "Cover Your Assets",
        problem:
          "document-driven design leads to obtuse requirements specifications",
        solution: "use blueprints",
      },
      "vendor-lock-in": {
        name: "Vendor Lock-In",
        aka: [
          "Product-Dependent Architecture",
          "Bondage and Submission",
          "Connector Conspiracy",
        ],
        problem: "systems are highly dependent on proprietary architectures",
        solution: "architectural isolation layers",
      },
      "architecture-by-implication": {
        name: "Architecture by Implication",
        aka: ["Wherefore Art Thou Architecture"],
        problem:
          "lack of architecture specification for systems under development",
        solution:
          "extensive modeling of the system from the viewpoints of different stakeholders",
      },
      "warm-bodies": {
        name: "Warm Bodies",
        aka: ["Deadwood", "Body Shop", "Seat Warmers", "Mythical Man-Month"],
        problem: "the vast majority of programmers do a tiny minority of work",
        solution:
          "the ideal team size is four people, the ideal project duration is four months",
      },
      "design-by-committee": {
        name: "Design by Committee",
        aka: [
          "Gold Plating",
          "Standards Disease",
          "Make Everybody Happy",
          "Political Party",
        ],
        problem: "complex and incoherent architectures",
        solution: "distinction of architecture roles and refactoring",
      },
      "swiss-army-knife": {
        name: "Swiss Army Knife",
        problem:
          "excessively complex interface meant to support too many use-cases",
        solution:
          "standardizing usage of a subset of the interface using a profile",
      },
      "reinvent-the-wheel": {
        name: "Reinvent The Wheel",
        aka: ["Design in a Vacuum", "Greenfield System"],
        problem:
          "custom software systems are built even when their functionality exists in legacy software",
        solution: "architecture mining",
      },
      "the-grand-old-duke-of-york": {
        name: "The Grand Old Duke of York",
        aka: [
          "Everyone Charges Up the Hill",
          "Lack of Architecture Instinct",
          "Abstractionist vs Implementationists",
        ],
        problem:
          "software designs which are unnecessarily complex with very little abstraction",
        solution: "distinction of architectural roles",
      },
    },
  },
  patterns: {
    creational: {
      "abstract-factory": {
        name: "Abstract Factory",
        intent: "factory that delegates to platform-specific factory",
        problem: "platform dependency encapsulation",
        structure:
          "abstract factory delegates to one of any number of factories to instantiate classes implementing the requested interface",
      },
      builder: {
        name: "Builder",
        intent: "separate the construction object into multiple steps",
        problem:
          "some objects may be very complex, requiring dynamic construction, or many objects may be constructed from a base configuration",
        structure:
          "the reader parses common input, the builder polymorphically creates many peculiar targets",
      },
      "factory-method": {
        name: "Factory Method",
        intent: "encapsulate class construction",
        problem:
          "allow applications to define the construction of their own domain objects",
        structure:
          "any constructor method, eg: named constructors, service container",
      },
      "object-pool": {
        name: "Object Pool",
        intent:
          "avoid expensive instantiation by caching and re-using created objects",
        problem:
          "object instantiation can be expensive, object pools cache instantiated objects to avoid recreating them",
        structure:
          "client request object from pool which instantiates it if none are available, and caches it for reuse when the client is finished",
      },
      prototype: {
        name: " Prototype",
        intent: "create objects by copying others",
        problem:
          "limit configuration management by construct a class once, then create more instances by copying",
        structure:
          "a factory knows how to find a pure, virtual prototype which can then clone itself",
      },
      singleton: {
        name: "Singleton",
        intent: "ensure a class has only one instance",
        problem:
          "the application needs to guarantee only one instance of a class exists",
        structure:
          "the singleton class provides a single accessor function which instantiates and caches the instance on first invocation",
      },
    },
    structural: {
      adapter: {
        name: "Adapter",
        intent: "wrap existing interface to a new interface",
        problem: "existing implementations might have awkward interfaces",
        structure:
          "the adapter exposes an api which simply invokes the wrapped class in a friendlier way",
      },
      bridge: {
        name: "Bridge",
        intent: "decouple abstraction from its implementation",
        problem:
          "support extending/composing the interface and the class independently",
        structure:
          "a class which implements all the necessary interfaces and delegates to the necessary implementations which don't adhere to those interfaces",
      },
      composite: {
        name: "Composite",
        intent: "treat individual objects or collections of objects uniformly",
        problem: "recursive, hierarchical structures may or may not terminate",
        structure:
          "the composite shares the APIs of both the object and collection",
      },
      decorator: {
        name: "Decorator",
        intent: "dynamically attach responsibilities to object",
        problem: "adding behavior/state to objects at runtime",
        structure:
          "when calling an interface method, actually call the wrapper's method, which calls the wrapped object's method and provides a side effect",
      },
      facade: {
        name: "Facade",
        intent: "unify multiple interfaces into a single interface",
        problem:
          "a complex collection of subsystems needs a simplified interface",
        structure:
          "a facade may call out to many subsystems with a single method",
      },
      flyweight: {
        name: "Flyweight",
        intent: "centralize/share uniform data across multiple objects",
        problem:
          "when dealing with many similar objects, you may have redundantly allocated data in memory",
        structure:
          "one object containing common state is stored in a factory's repository and shared among many objects which in themselves contain only unique state",
      },
      "private-class-data": {
        name: "Private Class Data",
        intent: "control write access to data",
        problem:
          "data may need to have strict controls over when and how it can be manipulated",
        structure:
          "instead of defining data directly on the target object, the target object is passed a stateful object in is constructor which can provide access controls on the state",
      },
      proxy: {
        name: "Proxy",
        intent: "provide a surrogate/placeholder object in place of another",
        problem:
          "provide support for an object before lazily instantiating it, delegate to an object stored elsewhere, mutate access/execution of state/behavior",
        structure:
          "instead of operating on the target class, the client operates on the proxy which fulfills the same interface, allowing the proxy to implement side effects",
      },
    },
    behavioral: {},
  },
};

export default content;
