type Navigation<T> = {
	[key: string]: Navigation<T> | T
}

type Lexicon = {
	[key: string]: string;
}

type AntiPattern = {
	name: string;
	aka?: string[];
	problem: string;
	solution: string;
}

export const index: Navigation<Lexicon | AntiPattern> = {
	lexicon: {
		"anti-pattern": "a coding practice which generates negative consequences",
		"far-coupled": "redundant or indirect associations.",
		"stovepipe": "systems with ad-hoc architectures"
	},
	"anti-patterns": {
		"software-development": {
			"the-blob": {
				name: "The Blob",
				aka: ["Winnebego", "God Class"],
				problem: "a single class comprising the majority of application responsibilities",
				solution: "refactoring design to distribute responsibilities and isolate change"
			},
			"continuous-obsolescense": {
				name: "Continuous Obsolescense",
				problem: "technology becomes obsolete faster than engineers can maintain it",
				solution: "design to interfaces/constracts which obscure the effect of obsolete implementations"
			},
			"lava-flow": {
				name: "Lava Flow",
				aka: ["Dead Code"],
				problem: "legacy, unreachable, commented, prototype, or etc. code which has not been refactored/removed and is no longer understood",
				solution: "code analysis, documentation, deletion, and refactoring/wrapping with configuration management"
			},
			"ambiguous-viewpoint": {
				name: "Ambiguous Viewpoint",
				problem: "Object-Oriented Analysis & Design models presented without respect to a distinct viewpoint: user, design, implementation",
				solution: "creating explicit and distinct models/diagrams of user, design, and implementation specifications"
			},
			"functional-decomposition": {
				name: "Functional Decomposition",
				aka: ["No OO"],
				problem: "object-oriented code written in a procedural structure",
				solution: "education and adherence to object-oriented design patterns"
			},
			"poltergeists": {
				name: "Poltergeists",
				aka: ["Gypsy", "Proliferation of Classes", "Big Dolt Controller Class"],
				problem: "classes with extremely limited roles/lifespans",
				solution: "reallocation of properties to more long-lived classes"
			},
			"boat-anchor": {
				name: "Boat Anchor",
				problem: "a piece of software/hardware which serves no meaningful purpose in the application",
				solution: "identification of a technical backup which can be implemented at low-cost"
			},
			"golden-hammer": {
				name: "Golden Hammer",
				aka: ["Old Yeller, Head-in-the-Sand"],
				problem: "the application of well-known but inappropriate technology to a given problem",
				solution: "training and architecture which supports the interoperability of multiple techolonigies"
			},
			"dead-end": {
				name: "Dead End",
				aka: ["Kevorkian Component"],
				problem: "the modification of vendor code such that it is no longer supported by the vendor",
				solution: "do not modify third-party applications, design to interfaces to avoid vendor lock-in"
			},
			"spaghetti-code": {
				name: "Spaghetti Code",
				problem: "code which is difficult to extend/maintain",
				solution: "frequent code refactoring and design review/maintenance"
			},
			"input-kludge": {
				name: "Input Kludge",
				problem: "ad-hoc input handling",
				solution: "industry-standard or framework-level input handling"
			},
			"walking-through-a-minefield": {
				name: "Walking Through a Minefield",
				problem: "all software has significant bugs",
				solution: "robust/excessive testing infrastructure"
			},
			"cut-and-paste-programming": {
				name: "Cut & Paste Programming",
				aka: ["Clipboard Coding", "Software Cloning", "Software Propagation"],
				problem: "code which is copied with minor or no modification",
				solution: "refactoring to reusable, configurable classes"
			},
			"mushroom-management": {
				name: "Mushroom Management",
				aka: ["Pseudo-Analysis", "Blind Development"],
				problem: "explicit policy of isolating developers from user feedback",
				solution: "UI/UX development in rapid, minor increments"
			}
		},
		"software-architecture": {
			"autogenerated-stovepipe": {
				name: "Autogenerated Stovepipe",
				problem: "when migrating to a distributed model, existing interfaces may make inefficient assuptions",
				solution: "full rewrite of interfaces"
			},
			"stovepipe-enterprise": {
				name: "Stovepipe Enterprise",
				aka: ["Islands of Automation"],
				problem: "software structure which inhibits change",
				solution: "selection and implementation of interoperability standards across systems and organizations"
			},
			"jumble": {
				name: "Jumble",
				problem: "reusability is inhibited by intermixing horizontal and vertical design elements",
				solution: "delegate horizontal design elements into their own layer"
			},
			"stovepipe-system": {
				name: "Stovepipe System",
				aka: ["Legacy System", "Uncle Sam Special", "Ad Hoc Integration"],
				problem: "ad-hoc, point-to-point subsystem integration",
				solution: "minimize exposed interfaces, rely on component-style abstractions"
			},
			"cover-your-assets": {
				name: "Cover Your Assets",
				problem: "document-driven design leads to obtuse requirements specifications",
				solution: "use blueprints"
			},
			"vendor-lock-in": {
				name: "Vendor Lock-In",
				aka: ["Product-Dependent Architecture", "Bondage and Submission", "Connector Conspiracy"],
				problem: "systems are highly dependent on proprietary architectures",
				solution: "architectual isolation layers"
			},
			"architecture-by-implecation": {
				name: "Architecture by Implecation",
				aka: ["Wherefore Art Thou Architecture"],
				problem: "lack of architecture specification for systems under development",
				solution: "extensive modeling of the system from the viewpoints of different stakeholders"
			},
			"warm-bodies": {
				name: "Warm Bodies",
				aka: ["Deadwood", "Body Shop", "Seat Warmers", "Mythical Man-Month"],
				problem: "the vast majority of programmers do a tiny minority of work",
				solution: "the ideal team size is four people, the ideal project duration is four months"
			},
			"design-by-committee": {
				name: "Design by Committee",
				aka: [""]
			}
		}
	}
};
